<script setup lang="ts">
const props = defineProps({
  to: String
})

const currentPath = useRoute().path
</script>

<template>
  <nav id="gvd-navigation" class="gvd-navigation govuk-clearfix" role="navigation" aria-labelledby="gvd-navigation-heading">
    <h1 class="govuk-visually-hidden" id="gvd-navigation-heading">Menu</h1>
    <ContentNavigation v-slot="{ navigation }">
      <ul class="gvd-navigation__list gvd-width-container">
        <li v-for="link of navigation.filter(n => n.title != 'Example page')" :key="link._path" class="gvd-navigation__list-item" :class="{'gvd-navigation__list-item--current': currentPath.startsWith(link._path)}">
          <NuxtLink :to="link._path" class="govuk-link govuk-link--no-visited-state govuk-link--no-underline app-navigation__link js-app-navigation__link">
            {{ link.title }}
          </NuxtLink>
        </li>
      </ul>
    </ContentNavigation>
  </nav>
</template>

<style lang="scss" scoped>
$govuk-is-ie8: false;
$govuk-new-link-styles: true;

@import '../node_modules/govuk-frontend/govuk/settings/colours-applied';
@import '../node_modules/govuk-frontend/govuk/settings/media-queries';
@import '../node_modules/govuk-frontend/govuk/helpers/media-queries';
@import './node_modules/govuk-frontend/govuk/settings/typography-font';
@import './node_modules/govuk-frontend/govuk/settings/typography-font-families';
@import './node_modules/govuk-frontend/govuk/settings/typography-responsive';
@import './node_modules/govuk-frontend/govuk/helpers/font-faces';
@import './node_modules/govuk-frontend/govuk/helpers/typography';
@import './node_modules/govuk-frontend/govuk/settings/links';
@import './node_modules/govuk-frontend/govuk/helpers/links';
@import './node_modules/govuk-frontend/govuk/settings/measurements';
@import './node_modules/govuk-frontend/govuk/helpers/focused';
@import './node_modules/govuk-frontend/govuk/settings/spacing';
@import './node_modules/govuk-frontend/govuk/helpers/spacing';
@import '../node_modules/govuk-frontend/govuk/tools/ie8';

$app-light-grey: #f8f8f8;

.gvd-navigation {
  border-bottom: 1px solid $govuk-border-colour;
  background-color: $app-light-grey;
}

.gvd-navigation__list {
  padding: 0;
  list-style: none;

  @include govuk-media-query($from: tablet) {
    position: relative;
    left: govuk-spacing(-3);
  }
}

.gvd-navigation__list-item {
  position: relative;

  @include govuk-media-query($from: tablet) {
    $navigation-height: 50px;

    @include govuk-font(19, $weight: bold, $line-height: $navigation-height);
    box-sizing: border-box;
    height: $navigation-height;
    height: govuk-px-to-rem($navigation-height);
    padding: 0 govuk-spacing(3);
    float: left;
  }
}

.gvd-navigation__list-item--current {
  @include govuk-media-query($from: tablet) {
    border-bottom: 4px solid govuk-colour("blue");
  }
}

.gvd-navigation__link,
.gvd-navigation__button {
  margin: govuk-spacing(3) 0;
  padding: 0;
  @include govuk-typography-weight-bold; // Override .govuk-link weight
  font-size: 19px; // We do not have a font mixin that produces 19px on mobile
  font-size: govuk-px-to-rem(19px);

  // Expand the touch area of the link to the full menu width
  &:after {
    content: "";
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
}

.gvd-navigation__link:not([hidden]) {
  display: inline-block;

  @include govuk-media-query($from: tablet) {
    display: inline;
  }
}

.gvd-navigation__button {
  @include govuk-link-common;
  @include govuk-link-style-no-underline;
  @include govuk-link-style-no-visited-state;
  border: 0;
  color: $govuk-link-colour;
  background-color: transparent;
}

.gvd-navigation__subnav {
  margin: 0 govuk-spacing(-3);
  padding: govuk-spacing(2) 0;
  background-color: govuk-colour("white");
  list-style: none;
}

.gvd-navigation__subnav--active {
  display: block;
}

.gvd-navigation__subnav,
.gvd-navigation__subnav--active {
  @include govuk-media-query($from: tablet) {
    display: none;
  }
}

.gvd-navigation__subnav-item {
  display: block;
  position: relative;
  padding: govuk-spacing(3);
}

.gvd-navigation__subnav-item--current {
  $_current-indicator-width: 4px;
  padding-left: govuk-spacing(4) - $_current-indicator-width;
  border-left: $_current-indicator-width solid govuk-colour("blue");
}

.gvd-navigation__theme {
  @include govuk-typography-common;
  position: relative; // this is to get around the artificial click area generated by the :after of the parent button
  margin: 0;
  padding: govuk-spacing(4) govuk-spacing(3) govuk-spacing(1);
  color: govuk-colour("dark-grey");
  // Font is defined as a hard 19px so
  // it does not re-size on mobile viewport
  font-size: 19px;
  font-size: govuk-px-to-rem(19px);
  font-weight: normal;
}

// overwrite govuk-header__menu-button's position and it displaying on tablet
.gvd-navigation__menu-button {
  top: auto;
  right: govuk-spacing(1);
  bottom: govuk-spacing(5);
}
</style>